spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: '{cipher}4c7238f4ca0c01a7c8ce2590dc08051cbef61079cdbfffb63e6429bafcce1f5d'
    password:

token:
  expiration_time: 86400000
  secret: user_token

order_service:
  # api-gateway service를 이용하는 방식
  # url: http://127.0.0.1:8000/order-service/api/v1/%s/orders

  # api-gateway를 이용하지 않는 방식
  # http://127.0.0.1:8000 대신 유레카에 등록된 마이크로서비스 이름을 등록하면 api-gateway를 거치지 않고 유레카 서버를 통해 마이크로서비스의 위치를 알아내 바로 요청을 보낼 수 있다.
  # discoveryService(localhost:8761) 에 접속해보면 등록된 이름이 보임 -> 대부분 application name의 대문자 형식
  # 이를 restTemplate이 인식하도록 하기 위해서는 restTemplate 빈 등록 시 @LoadBalanced 애노테이션을 붙여야 한다.
  url: http://ORDER-SERVICE/api/v1/%s/orders