spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: '{cipher}4c7238f4ca0c01a7c8ce2590dc08051cbef61079cdbfffb63e6429bafcce1f5d'
    password:

token:
  expiration_time: 86400000
  secret: user_token

order_service:
  # order-service는 유레카에 등록된 마이크로서비스 application name
  # restTemplate은 이를 인식하기 위해 빈 설정시 @LoadBalanced 애노테이션을 붙여야 한다.
  url: http://order-service/order-service/api/v1/%s/orders